using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace SpringfieldApp
{
    public partial class RulePage : Form
    {
        // just kept like that only if required
        // Location of python.exe                               --EDIT-THIS
        string pythonPath = "C:\\Users\\Wel11\\AppData\\Local\\Programs\\Python\\Python36-32\\python.exe";

        // Location of pythonScript                             --EDIT-THIS
        string scriptPath = "D:\\Harsh's Programs\\App\\C#Frontend\\testScript.py";

        // Location for temp Processed file to store            --EDIT-THIS
        string tempProcessedPath = "D:\\Harsh's Programs\\App\\C#Frontend\\tempProcessed.csv";

        public RulePage()
        {
            InitializeComponent();
        }

        private void enter_Click(object sender, EventArgs e)
        {
            string[] fields = keyfields.Lines;

            //output from the scripts
            string output = run_cmd(scriptPath, fields);

            //console ouput
            Console.WriteLine(output);

            //to display the output given by the python script called
            textarea.Text = output;

        }

        // method for calling python script
        //changes are required in this as we are passing the string[] array as args
        public string run_cmd(string cmd, string[] args)
        {
            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = pythonPath;
            // modification needed here
            start.Arguments = string.Format("\"{0}\" \"{1}\"", cmd, args);

            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)

            using (Process process = Process.Start(start))
            {
                // Here are the exceptions from our Python script
                string stderr = process.StandardError.ReadToEnd();

                // Here is the result of StdOut(for example: print("test"))
                //Here also modification is needed if you are returning string[]
                return process.StandardOutput.ReadToEnd();
            }
        }

    }
}
